version: '3.8'
services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - healthcare-network
    volumes:
      - ./logs:/app/logs
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=notification-service
    networks:
      - healthcare-network
networks:
  healthcare-network:
    driver: bridge
volumes:
  mongodb_data: